HW-done
Valentyn-Lukashuk/alfred_pennyworth pull request #8
Opened 2020-10-10 09:12 UTC by Valentyn-Lukashuk

2020-10-10 09:14 UTC, Valentyn-Lukashuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#3 - Advanced data types - Valentyn Lukashuk](https://trello.com/c/ZkMoyp3E/50-hw3-advanced-data-types-valentyn-lukashuk)

2020-10-12 19:57 UTC, dimigor requested changes

2020-10-12 19:57 UTC, dimigor commented on AdvancedDataTypes/homework/homework.py
> +        except KeyError:
при .pop() це виключення немає змісту

2020-10-12 19:57 UTC, dimigor commented on AdvancedDataTypes/homework/homework.py
> +    return data
створюй новий список, а не модифікуй минулий

2020-10-13 16:23 UTC, dimigor approved these changes

2020-10-13 16:23 UTC, dimigor commented on AdvancedDataTypes/homework/homework.py
> +        except KeyError:
Тобі не треба цей трай ексепт, бо якщо такого ключа не буде, то в іф програма не зайде

2020-10-14 15:43 UTC, merged